// ⚠️ PLACEHOLDER — REGENERATE BEFORE RUNNING AGAINST A REAL PROJECT.
//
// This file is normally generated by the FlutterFire CLI. The values below are
// dummy placeholders so the project compiles; the app will NOT connect to
// Firebase until you regenerate it:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// (See refactor_guide/DevOps.md.) `flutterfire configure` overwrites this file
// with your project's real options for every configured platform.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform — '
          'run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7GEEHmTjpK6IY1hJYW2sS6EFCo732ehU',
    appId: '1:291782873:web:308c5c1d4e52a9ba7fbec8',
    messagingSenderId: '291782873',
    projectId: 'myroom-ruby',
    authDomain: 'myroom-ruby.firebaseapp.com',
    storageBucket: 'myroom-ruby.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQovqJDOaeSo95rn3vJhzSzq3Lk3f5G0',
    appId: '1:291782873:android:9ad8f4d1dc4222e57fbec8',
    messagingSenderId: '291782873',
    projectId: 'myroom-ruby',
    storageBucket: 'myroom-ruby.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZHyu0JM4ZEu3aVmlbzE81qdtNkoNvb0',
    appId: '1:787435572031:ios:e8d818c79337bc57f0618a',
    messagingSenderId: '787435572031',
    projectId: 'myroom-da81b',
    storageBucket: 'myroom-da81b.firebasestorage.app',
    iosClientId: '787435572031-c3qpetrlm3l8tm2emjbagbt8b1phdip9.apps.googleusercontent.com',
    iosBundleId: 'com.myroom.myroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'myroom-app',
    storageBucket: 'myroom-app.appspot.com',
    iosBundleId: 'com.example.myroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS5QD8VXMkBJDxXW5pCX5d6-f6IdCmJEU',
    appId: '1:787435572031:web:154e23307b3bbd89f0618a',
    messagingSenderId: '787435572031',
    projectId: 'myroom-da81b',
    authDomain: 'myroom-da81b.firebaseapp.com',
    storageBucket: 'myroom-da81b.firebasestorage.app',
  );

}
